---

kube_vip_enabled: true

# HA for control-plane, requires a VIP
kube_vip_controlplane_enabled: true
kube_vip_address: 10.0.10.50
loadbalancer_apiserver:
  address: "{{ kube_vip_address }}"
  port: 6443
kube_vip_interface: ens192

# LoadBalancer for services
kube_vip_services_enabled: true
kube_vip_services_interface: ens192

kube_vip_arp_enabled: true
